export function Landing() {
  return <div className="landing">
    <header><a className="brand" href="#/"><span className="mark">S</span><span>SATCHETAK</span></a><nav><a href="#capabilities">What you can explore</a><a className="nav-cta" href="#/dashboard">Open dashboard ↗</a></nav></header>
    <main>
      <section className="landing-hero"><div><p className="eyebrow">A CLEARER VIEW OF EVERY ACRE</p><h1>Before you invest,<br />understand<br /><em>the land.</em></h1><p className="landing-intro">Turn a place on the map into an evidence-backed conversation. Explore vegetation, track land change, and know what to investigate next.</p><a className="primary-link" href="#/dashboard">Explore a location <span>↗</span></a><span className="hero-footnote">Agriculture & land development · Built around inspectable evidence</span></div><div className="land-art" role="img" aria-label="Illustrated land parcels with a highlighted area of interest"><div className="parcel parcel-one" /><div className="parcel parcel-two" /><div className="parcel parcel-three" /><div className="parcel parcel-four" /><div className="parcel-selection"><span>YOUR AREA OF INTEREST</span><i /><i /><i /><i /></div><div className="art-label"><span>LOCATION → OBSERVATION → EVIDENCE</span><strong>Every decision starts somewhere.</strong><small>Illustration · not satellite evidence</small></div></div></section>
      <div className="landing-strip"><span>01 <b>Choose your land</b></span><span>02 <b>Ask a useful question</b></span><span>03 <b>Inspect the evidence</b></span></div>
      <section id="capabilities" className="capabilities"><p className="eyebrow">ONE PLACE. DIFFERENT PERSPECTIVES.</p><h2>Questions that matter<br />on the ground.</h2><div className="capability-grid"><article><span className="capability-number">01 / AGRICULTURE</span><h3>Look beyond how green it looks.</h3><p>Compare vegetation across dates. Inspect decline, recovery, and variability before deciding where to investigate.</p><a href="#/dashboard">Explore vegetation ↗</a></article><article><span className="capability-number">02 / LAND & DEVELOPMENT</span><h3>See where the surface is changing.</h3><p>Screen land disturbance and large-area change with measured spectral evidence and clear limits on what it means.</p><a href="#/dashboard">Explore land change ↗</a></article><article><span className="capability-number">03 / PURCHASE SCREENING</span><h3>Know what you know. And what you don’t.</h3><p>Build a preliminary land report that separates measured changes from missing soil, water, title, and economic checks.</p><a href="#/dashboard">Start a land screen ↗</a></article></div></section>
      <section className="landing-bottom"><div><p className="eyebrow">EVIDENCE FIRST, ALWAYS</p><h2>A useful starting point.<br />An honest view of the unknowns.</h2><p>Start with a clearly labeled demo or connect live Copernicus observations. A satellite screen supports due diligence; it does not replace a site survey.</p></div><a className="primary-link" href="#/dashboard">Open your workspace ↗</a></section>
    </main><footer><span>SATCHETAK</span><span>Understand the land. Ask better questions.</span></footer>
  </div>
}
